apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster-cash
  region: eu-central-1
  
vpc:
  subnets:
    private:
      eu-central-1a: {id: subnet-0ca88944af576848a}
      eu-central-1b: {id: subnet-0ca88944af576848a}
    public:
      eu-central-1a: {id: subnet-0349387c3806ad96e}
      eu-central-1b: {id: subnet-0bcb471098831ac25}

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: false
    availabilityZones: ["eu-central-1a", "eu-central-1b"]

